デザイン講座LP作成
yanbaru-expert/yanbaru-expert-material-app pull request #291
Opened 2021-04-20 21:40 UTC by OhtakeYusuke

## issue 番号
Closes #10

## 実装内容
デザイン講座LP作成に伴う見た目、及び周辺機能
- LP見た目部分の作成
- デザイン講座関連バナーのリンク設置
- お問い合わせ機能の設置
- Stripeによる決済設置

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `bundle exec rubocop -a` を実行

## スクリーンショット（必要があれば）

## 備考
**ステージング環境下で確認できていること**
- お問い合わせ機能
- Stripeの決済画面までの移動

**ローカル・ステージング環境下で確認できていないこと**
- Stripeの決済後のページ遷移
- Stripeの決済後の決済完了通知メール

上記想定対応方法
実際に決済できるか、決済完了通知メールはStripe側のダッシュボード上でできないかを神里さんに相談済み。実施方法は未調査のためこれから調査。

2021-04-20 22:36 UTC, T-Tsujii requested changes

2021-04-20 22:36 UTC, T-Tsujii commented on app/mailers/contact_mailer.rb
> +  ADMIN_EMAIL = "yuyueureka157@gmail.com"
公開リポジトリですが，メールアドレスを公開しても問題ありませんでしょうか？

2021-04-20 22:36 UTC, T-Tsujii commented on app/controllers/contacts_controller.rb
> +    ContactMailer.admin_email(@contact).deliver_now
先に管理者に送信した方が無難だと思います。
ユーザーにだけ送信して管理者送信に失敗するのはかなりまずいパターンですので。

```suggestion
    ContactMailer.admin_email(@contact).deliver_now
    ContactMailer.user_email(@contact).deliver_now
```

2021-04-20 22:36 UTC, T-Tsujii commented on app/controllers/contacts_controller.rb
> +        puts "お問い合わせ送信失敗"
確認用であったと思いますので削っていただけますか。

```suggestion
```

2021-04-20 22:36 UTC, T-Tsujii commented on app/controllers/contacts_controller.rb
> +      if params[:message].length > 1000 || params[:name].length > 20 || params[:ruby_name].length > 30
可能性は少ないかもしれませんが，`params[:name]` は例えばアメリカの方ですと20文字オーバーは結構当たり前だと思います。

100文字ぐらいに設定されても良いのではないでしょうか。

2021-04-20 22:36 UTC, T-Tsujii commented on app/mailers/contact_mailer.rb
> +    end
こちらの方がまだ分かりやすいと思います。

```suggestion
    receiver = Rails.env.development? ? SAMPLE_EMAIL : ADMIN_EMAIL
```

もしくはこちらでしょうか。

```rb
    receiver = if Rails.env.development?
                 SAMPLE_EMAIL
               else
                 ADMIN_EMAIL
               end
```

2021-04-20 22:36 UTC, T-Tsujii commented on app/views/static_pages/design.html.erb
> +    <%= image_tag "design_course/design-fv.jpg" %>
画像ファイルをS3に配置しましたので，それぞれの頭に `https://d5izmuz0mcjzz.cloudfront.net/` を付けていただけますか。

追加画像がなければ，`app/assets/images/design_course` ディレクトリの削除もお願いします。

```suggestion
    <%= image_tag "https://d5izmuz0mcjzz.cloudfront.net/design_course/design-fv.jpg" %>
```

2021-04-20 22:36 UTC, T-Tsujii commented on config/initializers/mail.rb
> +}
こちらの形式でお願いします。

```suggestion
ActionMailer::Base.default_url_options = { host: host }

if Rails.env.production?
  # メール配信に失敗した場合にエラーを発生
  ActionMailer::Base.raise_delivery_errors = true
  ActionMailer::Base.delivery_method = :smtp
  ActionMailer::Base.smtp_settings = {
    port: 587,
    address: "smtp.gmail.com",
    user_name: Rails.application.credentials.gmail[:address],
    password: Rails.application.credentials.gmail[:password],
    domain: host,
    authentication: "plain",
  }
else
  ActionMailer::Base.delivery_method = :letter_opener_web
end
```

2021-04-21 00:20 UTC, OhtakeYusuke commented
## 修正内容
- 運営者メールアドレスをcredentials.ymlに格納
- お問い合わせ送信順序を管理者からに変更
- お問い合わせ失敗時確認のデバック用メッセージ削除
- お問い合わせの送信者名を20文字から100文字に変更
- 環境ごとの条件分岐を各リファクタリング
- 画像ファイルのS3への移行とファイルを以前まで格納してあったディレクトリごと削除
- rubocopによる修正
- ステージング環境へのpushと動作確認
- ステージング環境での画像表示確認


## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ]  bundle exec rubocop -a を実行

## 備考
いただいた提案通り修正しました。

2021-04-21 01:11 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-22 04:10 UTC, merged